### ISSUE TITLE
First review

### ISSUE THREAD

**Issue by rusdevops** [AnastasiaVern/BinarySearchTree#1]
@AnastasiaVern 
- [x] 1. Название метода не отражает действие которое оно совершает. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L76).
- [x] 2. Отсутствует проверка результата вызова оператора ввода. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L36) и [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L40).
- [x] 3. Необходимо придерживаться C++ стилю объявления указателей. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L63) и [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L102-L103).
- [x] 4. Стоит придерживаться одному стилю именования переменных. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L102) и [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L103).
- [x] 5. Отсутствует ключевое слово `noexcept`. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L76).
- [x] 6. Излишняя отладочная информация. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L157).
- [x] 7. Отсутствует инициализация членов данных в конструкторе. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L68). В следствие чего при вставке элементов происходит обращение к данным по не валидному указателю. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/include/BinarySearchTree.h#L113). 
- [x] 8. Подключение _(не нужного)_ заголовочного файла. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/examples/main.cpp#L1).
- [x] 9. Отсутствует проверка возвращаемого значения метода `find`. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/examples/main.cpp#L6).
- [x] 10. Присутствует избыточный код. [здесь](https://github.com/AnastasiaVern/BinarySearchTree/blob/b8da8fc2e48fef2dd192a57ab01c4d9baf95eb0f/examples/main.cpp#L11).

**Comment by AnastasiaVern** [comment]
1. https://en.wikipedia.org/wiki/Tree_traversal#Pre-order ( Pre-order - это прямой обход дерева, заключающийся в посещении корня и обходе левого и правого поддерева соответственно.Он и был реализован, если я Вас правильно поняла) 
2. Оператор >> теперь вызывается. 
3. Сделала (если я опять же правильно Вас поняла).
4. Не поняла :smiley: 
5. Сделала.
6. Убрала.
7. Сделала.
8. Убрала.
9.  Проверила. 
10. Убрала.

**Comment by rusdevops** [comment]
- Подсказка для устранения недочета, указанного в пункте `#2`: `if(in >> size)`.
- [Нажмите, чтобы понять пункт #4](https://tproger.ru/translations/camelcase-vs-underscores-scientific-showdown/).
- Что касается пункта `#7`, теперь в конструкторе по умолчанию отсутствует инициализация членов данных.
